package jp.co.cyms.base.export;

/*
 * Created on 26 Sep 2016 ( Time 16:37:06 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

import jp.co.cyms.apps.fam004.bean.Pam0041Bean;
import jp.co.cyms.apps.fam004.dao.Pam0041Dao;
import jp.co.cyms.base.BaseLogic;
import jp.co.cyms.common.Constant;

/**
 * Business Service Interface for entity SysParam.
 */
public class SysParamBL extends BaseLogic {
		
	
	
}
