/*
 * Created on 14 Dec 2016 ( Time 17:20:25 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package jp.co.cyms.db;

import java.io.Serializable;

import java.math.BigDecimal;
import java.util.Date;

/**
 * Java bean for 'BkgHdr' entity
 * 
 * @author DeNT
 *
 */
public class BkgHdrBean implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    // DB : SYSTEM_ID VARCHAR2 
    private String systemId;
    // DB : BOOKING_NO VARCHAR2 
    private String bookingNo;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    // DB : UPDATED_USER VARCHAR2 
    private String updatedUser;

    // DB : UPDATED_DT_UTC TIMESTAMP(6) 
    private Date updatedDtUtc;

    // DB : UPDATED_DT_SERVER TIMESTAMP(6) 
    private Date updatedDtServer;

    // DB : UPDATED_DT_LOCAL TIMESTAMP(6) 
    private Date updatedDtLocal;

    // DB : EXCLUSIVE_FG CHAR 
    private String exclusiveFg;

    // DB : VALIDATION_FLG CHAR 
    private String validationFlg;

    // DB : SHIPMENT_NO VARCHAR2 
    private String shipmentNo;

    // DB : BOOKING_DATE TIMESTAMP(6) 
    private Date bookingDate;

    // DB : BOOKING_REF_NO1 VARCHAR2 
    private String bookingRefNo1;

    // DB : BOOKING_REF_NO2 VARCHAR2 
    private String bookingRefNo2;

    // DB : SHIPPER VARCHAR2 
    private String shipper;

    // DB : DISCHARGE_PORT VARCHAR2 
    private String dischargePort;

    // DB : ETA TIMESTAMP(6) 
    private Date eta;

    // DB : CONSIGNEE VARCHAR2 
    private String consignee;

    // DB : FT_QTY20 NUMBER 
    private BigDecimal ftQty20;

    // DB : FT_QTY40 NUMBER 
    private BigDecimal ftQty40;

    // DB : DEPOT VARCHAR2 
    private String depot;

    // DB : REMARKS VARCHAR2 
    private String remarks;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setSystemId( String systemId ) {
        this.systemId = systemId ;
    }

    public String getSystemId() {
        return this.systemId;
    }

    public void setBookingNo( String bookingNo ) {
        this.bookingNo = bookingNo ;
    }

    public String getBookingNo() {
        return this.bookingNo;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setUpdatedUser( String updatedUser ) {
        this.updatedUser = updatedUser;
    }
    public String getUpdatedUser() {
        return this.updatedUser;
    }

    public void setUpdatedDtUtc( Date updatedDtUtc ) {
        this.updatedDtUtc = updatedDtUtc;
    }
    public Date getUpdatedDtUtc() {
        return this.updatedDtUtc;
    }

    public void setUpdatedDtServer( Date updatedDtServer ) {
        this.updatedDtServer = updatedDtServer;
    }
    public Date getUpdatedDtServer() {
        return this.updatedDtServer;
    }

    public void setUpdatedDtLocal( Date updatedDtLocal ) {
        this.updatedDtLocal = updatedDtLocal;
    }
    public Date getUpdatedDtLocal() {
        return this.updatedDtLocal;
    }

    public void setExclusiveFg( String exclusiveFg ) {
        this.exclusiveFg = exclusiveFg;
    }
    public String getExclusiveFg() {
        return this.exclusiveFg;
    }

    public void setValidationFlg( String validationFlg ) {
        this.validationFlg = validationFlg;
    }
    public String getValidationFlg() {
        return this.validationFlg;
    }

    public void setShipmentNo( String shipmentNo ) {
        this.shipmentNo = shipmentNo;
    }
    public String getShipmentNo() {
        return this.shipmentNo;
    }

    public void setBookingDate( Date bookingDate ) {
        this.bookingDate = bookingDate;
    }
    public Date getBookingDate() {
        return this.bookingDate;
    }

    public void setBookingRefNo1( String bookingRefNo1 ) {
        this.bookingRefNo1 = bookingRefNo1;
    }
    public String getBookingRefNo1() {
        return this.bookingRefNo1;
    }

    public void setBookingRefNo2( String bookingRefNo2 ) {
        this.bookingRefNo2 = bookingRefNo2;
    }
    public String getBookingRefNo2() {
        return this.bookingRefNo2;
    }

    public void setShipper( String shipper ) {
        this.shipper = shipper;
    }
    public String getShipper() {
        return this.shipper;
    }

    public void setDischargePort( String dischargePort ) {
        this.dischargePort = dischargePort;
    }
    public String getDischargePort() {
        return this.dischargePort;
    }

    public void setEta( Date eta ) {
        this.eta = eta;
    }
    public Date getEta() {
        return this.eta;
    }

    public void setConsignee( String consignee ) {
        this.consignee = consignee;
    }
    public String getConsignee() {
        return this.consignee;
    }

    public void setFtQty20( BigDecimal ftQty20 ) {
        this.ftQty20 = ftQty20;
    }
    public BigDecimal getFtQty20() {
        return this.ftQty20;
    }

    public void setFtQty40( BigDecimal ftQty40 ) {
        this.ftQty40 = ftQty40;
    }
    public BigDecimal getFtQty40() {
        return this.ftQty40;
    }

    public void setDepot( String depot ) {
        this.depot = depot;
    }
    public String getDepot() {
        return this.depot;
    }

    public void setRemarks( String remarks ) {
        this.remarks = remarks;
    }
    public String getRemarks() {
        return this.remarks;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(systemId);
        sb.append("|");
        sb.append(updatedUser);
        sb.append("|");
        sb.append(updatedDtUtc);
        sb.append("|");
        sb.append(updatedDtServer);
        sb.append("|");
        sb.append(updatedDtLocal);
        sb.append("|");
        sb.append(exclusiveFg);
        sb.append("|");
        sb.append(bookingNo);
        sb.append("|");
        sb.append(validationFlg);
        sb.append("|");
        sb.append(shipmentNo);
        sb.append("|");
        sb.append(bookingDate);
        sb.append("|");
        sb.append(bookingRefNo1);
        sb.append("|");
        sb.append(bookingRefNo2);
        sb.append("|");
        sb.append(shipper);
        sb.append("|");
        sb.append(dischargePort);
        sb.append("|");
        sb.append(eta);
        sb.append("|");
        sb.append(consignee);
        sb.append("|");
        sb.append(ftQty20);
        sb.append("|");
        sb.append(ftQty40);
        sb.append("|");
        sb.append(depot);
        sb.append("|");
        sb.append(remarks);
        return sb.toString(); 
    } 


}
