/*
 * Created on 14 Dec 2016 ( Time 17:20:30 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package jp.co.cyms.db;

import java.io.Serializable;

import java.math.BigDecimal;
import java.util.Date;

/**
 * Java bean for 'BkgScd' entity
 * 
 * @author DeNT
 *
 */
public class BkgScd implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    // DB : SYSTEM_ID VARCHAR2 
    private String systemId;
    // DB : BOOKING_NO VARCHAR2 
    private String bookingNo;
    // DB : JOB_PATTERN VARCHAR2 
    private String jobPattern;
    // DB : JOB_DATE TIMESTAMP(6) 
    private Date jobDate;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    // DB : UPDATED_USER VARCHAR2 
    private String updatedUser;

    // DB : UPDATED_DT_UTC TIMESTAMP(6) 
    private Date updatedDtUtc;

    // DB : UPDATED_DT_SERVER TIMESTAMP(6) 
    private Date updatedDtServer;

    // DB : UPDATED_DT_LOCAL TIMESTAMP(6) 
    private Date updatedDtLocal;

    // DB : EXCLUSIVE_FG CHAR 
    private String exclusiveFg;

    // DB : VALIDATION_FLG CHAR 
    private String validationFlg;

    // DB : FT_QTY20 NUMBER 
    private BigDecimal ftQty20;

    // DB : FT_QTY40 NUMBER 
    private BigDecimal ftQty40;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setSystemId( String systemId ) {
        this.systemId = systemId ;
    }

    public String getSystemId() {
        return this.systemId;
    }

    public void setBookingNo( String bookingNo ) {
        this.bookingNo = bookingNo ;
    }

    public String getBookingNo() {
        return this.bookingNo;
    }

    public void setJobPattern( String jobPattern ) {
        this.jobPattern = jobPattern ;
    }

    public String getJobPattern() {
        return this.jobPattern;
    }

    public void setJobDate( Date jobDate ) {
        this.jobDate = jobDate ;
    }

    public Date getJobDate() {
        return this.jobDate;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setUpdatedUser( String updatedUser ) {
        this.updatedUser = updatedUser;
    }
    public String getUpdatedUser() {
        return this.updatedUser;
    }

    public void setUpdatedDtUtc( Date updatedDtUtc ) {
        this.updatedDtUtc = updatedDtUtc;
    }
    public Date getUpdatedDtUtc() {
        return this.updatedDtUtc;
    }

    public void setUpdatedDtServer( Date updatedDtServer ) {
        this.updatedDtServer = updatedDtServer;
    }
    public Date getUpdatedDtServer() {
        return this.updatedDtServer;
    }

    public void setUpdatedDtLocal( Date updatedDtLocal ) {
        this.updatedDtLocal = updatedDtLocal;
    }
    public Date getUpdatedDtLocal() {
        return this.updatedDtLocal;
    }

    public void setExclusiveFg( String exclusiveFg ) {
        this.exclusiveFg = exclusiveFg;
    }
    public String getExclusiveFg() {
        return this.exclusiveFg;
    }

    public void setValidationFlg( String validationFlg ) {
        this.validationFlg = validationFlg;
    }
    public String getValidationFlg() {
        return this.validationFlg;
    }

    public void setFtQty20( BigDecimal ftQty20 ) {
        this.ftQty20 = ftQty20;
    }
    public BigDecimal getFtQty20() {
        return this.ftQty20;
    }

    public void setFtQty40( BigDecimal ftQty40 ) {
        this.ftQty40 = ftQty40;
    }
    public BigDecimal getFtQty40() {
        return this.ftQty40;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(systemId);
        sb.append("|");
        sb.append(updatedUser);
        sb.append("|");
        sb.append(updatedDtUtc);
        sb.append("|");
        sb.append(updatedDtServer);
        sb.append("|");
        sb.append(updatedDtLocal);
        sb.append("|");
        sb.append(exclusiveFg);
        sb.append("|");
        sb.append(bookingNo);
        sb.append("|");
        sb.append(jobPattern);
        sb.append("|");
        sb.append(jobDate);
        sb.append("|");
        sb.append(validationFlg);
        sb.append("|");
        sb.append(ftQty20);
        sb.append("|");
        sb.append(ftQty40);
        return sb.toString(); 
    } 


}
