/*
 * Created on 14 Dec 2016 ( Time 17:20:35 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package jp.co.cyms.db;

import java.io.Serializable;

import java.util.Date;

/**
 * Java bean for 'DrvJob' entity
 * 
 * @author DeNT
 *
 */
public class DrvJobBean implements Serializable {

    private static final long serialVersionUID = 1L;

    // DB : FROM_PLACE VARCHAR2 
    private String fromPlace;

    // DB : VIA_PLACE VARCHAR2 
    private String viaPlace;

    // DB : TO_PLACE VARCHAR2 
    private String toPlace;

    // DB : PICK_PLACE VARCHAR2
    private String pickPlace;

    // DB : DELIVERY_PLACE VARCHAR2 
    private String deliveryPlace;

	/** Time zone */
	private int timeZone;

    /**
	 * @return the fromPlace
	 */
	public String getFromPlace() {
		return fromPlace;
	}

	/**
	 * @param fromPlace the fromPlace to set
	 */
	public void setFromPlace(String fromPlace) {
		this.fromPlace = fromPlace;
	}

	/**
	 * @return the viaPlace
	 */
	public String getViaPlace() {
		return viaPlace;
	}

	/**
	 * @param viaPlace the viaPlace to set
	 */
	public void setViaPlace(String viaPlace) {
		this.viaPlace = viaPlace;
	}

	/**
	 * @return the toPlace
	 */
	public String getToPlace() {
		return toPlace;
	}

	/**
	 * @param toPlace the toPlace to set
	 */
	public void setToPlace(String toPlace) {
		this.toPlace = toPlace;
	}

	/**
	 * @return the pickPlace
	 */
	public String getPickPlace() {
		return pickPlace;
	}

	/**
	 * @param pickPlace the pickPlace to set
	 */
	public void setPickPlace(String pickPlace) {
		this.pickPlace = pickPlace;
	}

	/**
	 * @return the deliveryPlace
	 */
	public String getDeliveryPlace() {
		return deliveryPlace;
	}

	/**
	 * @param deliveryPlace the deliveryPlace to set
	 */
	public void setDeliveryPlace(String deliveryPlace) {
		this.deliveryPlace = deliveryPlace;
	}

	/**
	 * @return the timeZone
	 */
	public int getTimeZone() {
		return timeZone;
	}

	/**
	 * @param timeZone the timeZone to set
	 */
	public void setTimeZone(int timeZone) {
		this.timeZone = timeZone;
	}


	//----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    // DB : SYSTEM_ID VARCHAR2 
    private String systemId;
    // DB : DRIVER_ID VARCHAR2 
    private String driverId;
    // DB : JOB_NO VARCHAR2 
    private String jobNo;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    // DB : UPDATED_USER VARCHAR2 
    private String updatedUser;

    // DB : UPDATED_DT_UTC TIMESTAMP(6) 
    private Date updatedDtUtc;

    // DB : UPDATED_DT_SERVER TIMESTAMP(6) 
    private Date updatedDtServer;

    // DB : UPDATED_DT_LOCAL TIMESTAMP(6) 
    private int updatedDtLocal;

    // DB : EXCLUSIVE_FG CHAR 
    private String exclusiveFg;

    // DB : JOB_PROGRESS VARCHAR2 
    private String jobProgress;

    // DB : JOB_DATE TIMESTAMP(6) 
    private String jobDate;

    // DB : START_TME_PLANNED TIMESTAMP(6) 
    private String startTimePlanned;

    // DB : END_TIME_PLANNED TIMESTAMP(6) 
    private String endTimePlanned;

    // DB : JOB_PATTERN VARCHAR2 
    private String jobPattern;

    // DB : CONTAINER_SIZE VARCHAR2 
    private String containerSize;

    // DB : TABLET_ID VARCHAR2 
    private String tabletId;

    // DB : BOOKING_NO VARCHAR2 
    private String bookingNo;

    // DB : CONTAINER_NO VARCHAR2 
    private String containerNo;

    // DB : HEAD_NO VARCHAR2 
    private String headNo;

    // DB : CHASSIS_NO VARCHAR2 
    private String chassisNo;

    // DB : DEPARTURE_TIME_FROM TIMESTAMP(6) 
    private Date departureTimeFrom;

    // DB : ARRIVAL_TIME_VIA TIMESTAMP(6) 
    private Date arrivalTimeVia;

    // DB : DEPARTURE_TIME_VIA TIMESTAMP(6) 
    private Date departureTimeVia;

    // DB : ARRIVAL_TIME_TO TIMESTAMP(6) 
    private Date arrivalTimeTo;

    // DB : COMPLETED_TIME TIMESTAMP(6) 
    private Date completedTime;

    // DB : DOCKING_TIME TIMESTAMP(6) 
    private Date dockingTime;

    // DB : LIFT_ON_TIME TIMESTAMP(6) 
    private Date liftOnTime;

    // DB : RELEASE_TIME TIMESTAMP(6) 
    private Date releaseTime;

    // DB : LIFT_OFF_TIME TIMESTAMP(6) 
    private Date liftOffTime;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setSystemId( String systemId ) {
        this.systemId = systemId ;
    }

    public String getSystemId() {
        return this.systemId;
    }

    public void setDriverId( String driverId ) {
        this.driverId = driverId ;
    }

    public String getDriverId() {
        return this.driverId;
    }

    public void setJobNo( String jobNo ) {
        this.jobNo = jobNo ;
    }

    public String getJobNo() {
        return this.jobNo;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setUpdatedUser( String updatedUser ) {
        this.updatedUser = updatedUser;
    }
    public String getUpdatedUser() {
        return this.updatedUser;
    }

    public void setUpdatedDtUtc( Date updatedDtUtc ) {
        this.updatedDtUtc = updatedDtUtc;
    }
    public Date getUpdatedDtUtc() {
        return this.updatedDtUtc;
    }

    public void setUpdatedDtServer( Date updatedDtServer ) {
        this.updatedDtServer = updatedDtServer;
    }
    public Date getUpdatedDtServer() {
        return this.updatedDtServer;
    }

    public void setUpdatedDtLocal( int updatedDtLocal ) {
        this.updatedDtLocal = updatedDtLocal;
    }
    public int getUpdatedDtLocal() {
        return this.updatedDtLocal;
    }

    public void setExclusiveFg( String exclusiveFg ) {
        this.exclusiveFg = exclusiveFg;
    }
    public String getExclusiveFg() {
        return this.exclusiveFg;
    }

    public void setJobProgress( String jobProgress ) {
        this.jobProgress = jobProgress;
    }
    public String getJobProgress() {
        return this.jobProgress;
    }

    public void setJobDate( String jobDate ) {
        this.jobDate = jobDate;
    }
    public String getJobDate() {
        return this.jobDate;
    }

    public void setStartTimePlanned( String startTimePlanned ) {
        this.startTimePlanned = startTimePlanned;
    }
    public String getStartTimePlanned() {
        return this.startTimePlanned;
    }

    public void setEndTimePlanned( String endTimePlanned ) {
        this.endTimePlanned = endTimePlanned;
    }
    public String getEndTimePlanned() {
        return this.endTimePlanned;
    }

    public void setJobPattern( String jobPattern ) {
        this.jobPattern = jobPattern;
    }
    public String getJobPattern() {
        return this.jobPattern;
    }

    public void setContainerSize( String containerSize ) {
        this.containerSize = containerSize;
    }
    public String getContainerSize() {
        return this.containerSize;
    }

    public void setTabletId( String tabletId ) {
        this.tabletId = tabletId;
    }
    public String getTabletId() {
        return this.tabletId;
    }
    
    public void setBookingNo( String bookingNo ) {
        this.bookingNo = bookingNo;
    }
    public String getBookingNo() {
        return this.bookingNo;
    }

    public void setContainerNo( String containerNo ) {
        this.containerNo = containerNo;
    }
    public String getContainerNo() {
        return this.containerNo;
    }

    public void setHeadNo( String headNo ) {
        this.headNo = headNo;
    }
    public String getHeadNo() {
        return this.headNo;
    }

    public void setChassisNo( String chassisNo ) {
        this.chassisNo = chassisNo;
    }
    public String getChassisNo() {
        return this.chassisNo;
    }

    public void setDepartureTimeFrom( Date departureTimeFrom ) {
        this.departureTimeFrom = departureTimeFrom;
    }
    public Date getDepartureTimeFrom() {
        return this.departureTimeFrom;
    }

    public void setArrivalTimeVia( Date arrivalTimeVia ) {
        this.arrivalTimeVia = arrivalTimeVia;
    }
    public Date getArrivalTimeVia() {
        return this.arrivalTimeVia;
    }

    public void setDepartureTimeVia( Date departureTimeVia ) {
        this.departureTimeVia = departureTimeVia;
    }
    public Date getDepartureTimeVia() {
        return this.departureTimeVia;
    }

    public void setArrivalTimeTo( Date arrivalTimeTo ) {
        this.arrivalTimeTo = arrivalTimeTo;
    }
    public Date getArrivalTimeTo() {
        return this.arrivalTimeTo;
    }

    public void setCompletedTime( Date completedTime ) {
        this.completedTime = completedTime;
    }
    public Date getCompletedTime() {
        return this.completedTime;
    }

    public void setDockingTime( Date dockingTime ) {
        this.dockingTime = dockingTime;
    }
    public Date getDockingTime() {
        return this.dockingTime;
    }

    public void setLiftOnTime( Date liftOnTime ) {
        this.liftOnTime = liftOnTime;
    }
    public Date getLiftOnTime() {
        return this.liftOnTime;
    }

    public void setReleaseTime( Date releaseTime ) {
        this.releaseTime = releaseTime;
    }
    public Date getReleaseTime() {
        return this.releaseTime;
    }

    public void setLiftOffTime( Date liftOffTime ) {
        this.liftOffTime = liftOffTime;
    }
    public Date getLiftOffTime() {
        return this.liftOffTime;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(systemId);
        sb.append("|");
        sb.append(updatedUser);
        sb.append("|");
        sb.append(updatedDtUtc);
        sb.append("|");
        sb.append(updatedDtServer);
        sb.append("|");
        sb.append(updatedDtLocal);
        sb.append("|");
        sb.append(exclusiveFg);
        sb.append("|");
        sb.append(driverId);
        sb.append("|");
        sb.append(jobNo);
        sb.append("|");
        sb.append(jobProgress);
        sb.append("|");
        sb.append(jobDate);
        sb.append("|");
        sb.append(startTimePlanned);
        sb.append("|");
        sb.append(endTimePlanned);
        sb.append("|");
        sb.append(jobPattern);
        sb.append("|");
        sb.append(containerSize);
        sb.append("|");
        sb.append(tabletId);
        sb.append("|");
        sb.append(bookingNo);
        sb.append("|");
        sb.append(containerNo);
        sb.append("|");
        sb.append(headNo);
        sb.append("|");
        sb.append(chassisNo);
        sb.append("|");
        sb.append(departureTimeFrom);
        sb.append("|");
        sb.append(arrivalTimeVia);
        sb.append("|");
        sb.append(departureTimeVia);
        sb.append("|");
        sb.append(arrivalTimeTo);
        sb.append("|");
        sb.append(completedTime);
        sb.append("|");
        sb.append(dockingTime);
        sb.append("|");
        sb.append(liftOnTime);
        sb.append("|");
        sb.append(releaseTime);
        sb.append("|");
        sb.append(liftOffTime);
        return sb.toString(); 
    } 


}
