/*
 * Created on 14 Dec 2016 ( Time 17:20:46 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package jp.co.cyms.db;

import java.io.Serializable;

import java.util.Date;

/**
 * Java bean for 'GpsNow' entity
 * 
 * @author DeNT
 *
 */
public class GpsNow implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    // DB : SYSTEM_ID VARCHAR2 
    private String systemId;
    // DB : TABLET_ID VARCHAR2 
    private String tabletId;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    // DB : TIMESTAMP TIMESTAMP(6) 
    private Date timestamp;

    // DB : DRIVER_ID VARCHAR2 
    private String driverId;

    // DB : LAST_LATITUDE FLOAT 
    private Double lastLatitude;

    // DB : LAST_LONGITUDE FLOAT 
    private Double lastLongitude;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setSystemId( String systemId ) {
        this.systemId = systemId ;
    }

    public String getSystemId() {
        return this.systemId;
    }

    public void setTabletId( String tabletId ) {
        this.tabletId = tabletId ;
    }

    public String getTabletId() {
        return this.tabletId;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setTimestamp( Date timestamp ) {
        this.timestamp = timestamp;
    }
    public Date getTimestamp() {
        return this.timestamp;
    }

    public void setDriverId( String driverId ) {
        this.driverId = driverId;
    }
    public String getDriverId() {
        return this.driverId;
    }

    public void setLastLatitude( Double lastLatitude ) {
        this.lastLatitude = lastLatitude;
    }
    public Double getLastLatitude() {
        return this.lastLatitude;
    }

    public void setLastLongitude( Double lastLongitude ) {
        this.lastLongitude = lastLongitude;
    }
    public Double getLastLongitude() {
        return this.lastLongitude;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(systemId);
        sb.append("|");
        sb.append(tabletId);
        sb.append("|");
        sb.append(timestamp);
        sb.append("|");
        sb.append(driverId);
        sb.append("|");
        sb.append(lastLatitude);
        sb.append("|");
        sb.append(lastLongitude);
        return sb.toString(); 
    } 


}
