/*
 * Created on 14 Dec 2016 ( Time 17:21:01 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package jp.co.cyms.db;

import java.io.Serializable;

import java.util.Date;

/**
 * Java bean for 'JptMstH2' entity
 * 
 * @author DeNT
 *
 */
public class JptMstH2 implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    // DB : SYSTEM_ID VARCHAR2 
    private String systemId;
    // DB : JOB_PATTERN_CD VARCHAR2 
    private String jobPatternCd;
    // DB : CLASS VARCHAR2 
    private String classCd;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    // DB : PLACE_CD VARCHAR2 
    private String placeCd;

    // DB : DOCUMENT_1 VARCHAR2 
    private String document1;

    // DB : DOCUMENT_2 VARCHAR2 
    private String document2;

    // DB : DOCUMENT_3 VARCHAR2 
    private String document3;

    // DB : DOCUMENT_4 VARCHAR2 
    private String document4;

    // DB : UPDATED_USER VARCHAR2 
    private String updatedUser;

    // DB : UPDATED_DT_UTC DATE 
    private Date updatedDtUtc;

    // DB : UPDATED_DT_SERVER DATE 
    private Date updatedDtServer;

    // DB : EXCLUSIVE_FG CHAR 
    private String exclusiveFg;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setSystemId( String systemId ) {
        this.systemId = systemId ;
    }

    public String getSystemId() {
        return this.systemId;
    }

    public void setJobPatternCd( String jobPatternCd ) {
        this.jobPatternCd = jobPatternCd ;
    }

    public String getJobPatternCd() {
        return this.jobPatternCd;
    }

    public void setClassCd( String classCd ) {
        this.classCd = classCd ;
    }

    public String getClassCd() {
        return this.classCd;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setPlaceCd( String placeCd ) {
        this.placeCd = placeCd;
    }
    public String getPlaceCd() {
        return this.placeCd;
    }

    public void setDocument1( String document1 ) {
        this.document1 = document1;
    }
    public String getDocument1() {
        return this.document1;
    }

    public void setDocument2( String document2 ) {
        this.document2 = document2;
    }
    public String getDocument2() {
        return this.document2;
    }

    public void setDocument3( String document3 ) {
        this.document3 = document3;
    }
    public String getDocument3() {
        return this.document3;
    }

    public void setDocument4( String document4 ) {
        this.document4 = document4;
    }
    public String getDocument4() {
        return this.document4;
    }

    public void setUpdatedUser( String updatedUser ) {
        this.updatedUser = updatedUser;
    }
    public String getUpdatedUser() {
        return this.updatedUser;
    }

    public void setUpdatedDtUtc( Date updatedDtUtc ) {
        this.updatedDtUtc = updatedDtUtc;
    }
    public Date getUpdatedDtUtc() {
        return this.updatedDtUtc;
    }

    public void setUpdatedDtServer( Date updatedDtServer ) {
        this.updatedDtServer = updatedDtServer;
    }
    public Date getUpdatedDtServer() {
        return this.updatedDtServer;
    }

    public void setExclusiveFg( String exclusiveFg ) {
        this.exclusiveFg = exclusiveFg;
    }
    public String getExclusiveFg() {
        return this.exclusiveFg;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(systemId);
        sb.append("|");
        sb.append(jobPatternCd);
        sb.append("|");
        sb.append(classCd);
        sb.append("|");
        sb.append(placeCd);
        sb.append("|");
        sb.append(document1);
        sb.append("|");
        sb.append(document2);
        sb.append("|");
        sb.append(document3);
        sb.append("|");
        sb.append(document4);
        sb.append("|");
        sb.append(updatedUser);
        sb.append("|");
        sb.append(updatedDtUtc);
        sb.append("|");
        sb.append(updatedDtServer);
        sb.append("|");
        sb.append(exclusiveFg);
        return sb.toString(); 
    } 


}
