/*
 * Created on 14 Dec 2016 ( Time 17:20:51 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package jp.co.cyms.db;

import java.io.Serializable;

import java.util.Date;

/**
 * Java bean for 'JptMstD' entity
 * 
 * @author DeNT
 *
 */
public class JptMstD implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    // DB : SYSTEM_ID VARCHAR2 
    private String systemId;
    // DB : JOB_PATTERN_CD VARCHAR2 
    private String jobPatternCd;
    // DB : CLASS VARCHAR2 
    private String classCd;
    // DB : DRIVER_TYPE VARCHAR2 
    private String driverType;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    // DB : CONTAINER_FG1 VARCHAR2 
    private String containerFg1;

    // DB : CONTAINER_FG2 VARCHAR2 
    private String containerFg2;

    // DB : CHASSIS_FG1 VARCHAR2 
    private String chassisFg1;

    // DB : CHASSIS_FG2 VARCHAR2 
    private String chassisFg2;

    // DB : DOCKING_FG1 VARCHAR2 
    private String dockingFg1;

    // DB : DOCKING_FG2 VARCHAR2 
    private String dockingFg2;

    // DB : RELEASE_FG1 VARCHAR2 
    private String releaseFg1;

    // DB : RELEASE_FG2 VARCHAR2 
    private String releaseFg2;

    // DB : LIFT_ON_FG1 VARCHAR2 
    private String liftOnFg1;

    // DB : LIFT_ON_FG2 VARCHAR2 
    private String liftOnFg2;

    // DB : LIFT_OFF_FG1 VARCHAR2 
    private String liftOffFg1;

    // DB : LIFT_OFF_FG2 VARCHAR2 
    private String liftOffFg2;

    // DB : UPDATED_USER VARCHAR2 
    private String updatedUser;

    // DB : UPDATED_DT_UTC DATE 
    private Date updatedDtUtc;

    // DB : UPDATED_DT_SERVER DATE 
    private Date updatedDtServer;

    // DB : EXCLUSIVE_FG CHAR 
    private String exclusiveFg;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setSystemId( String systemId ) {
        this.systemId = systemId ;
    }

    public String getSystemId() {
        return this.systemId;
    }

    public void setJobPatternCd( String jobPatternCd ) {
        this.jobPatternCd = jobPatternCd ;
    }

    public String getJobPatternCd() {
        return this.jobPatternCd;
    }

    public void setClassCd( String classCd ) {
        this.classCd = classCd ;
    }

    public String getClassCd() {
        return this.classCd;
    }

    public void setDriverType( String driverType ) {
        this.driverType = driverType ;
    }

    public String getDriverType() {
        return this.driverType;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setContainerFg1( String containerFg1 ) {
        this.containerFg1 = containerFg1;
    }
    public String getContainerFg1() {
        return this.containerFg1;
    }

    public void setContainerFg2( String containerFg2 ) {
        this.containerFg2 = containerFg2;
    }
    public String getContainerFg2() {
        return this.containerFg2;
    }

    public void setChassisFg1( String chassisFg1 ) {
        this.chassisFg1 = chassisFg1;
    }
    public String getChassisFg1() {
        return this.chassisFg1;
    }

    public void setChassisFg2( String chassisFg2 ) {
        this.chassisFg2 = chassisFg2;
    }
    public String getChassisFg2() {
        return this.chassisFg2;
    }

    public void setDockingFg1( String dockingFg1 ) {
        this.dockingFg1 = dockingFg1;
    }
    public String getDockingFg1() {
        return this.dockingFg1;
    }

    public void setDockingFg2( String dockingFg2 ) {
        this.dockingFg2 = dockingFg2;
    }
    public String getDockingFg2() {
        return this.dockingFg2;
    }

    public void setReleaseFg1( String releaseFg1 ) {
        this.releaseFg1 = releaseFg1;
    }
    public String getReleaseFg1() {
        return this.releaseFg1;
    }

    public void setReleaseFg2( String releaseFg2 ) {
        this.releaseFg2 = releaseFg2;
    }
    public String getReleaseFg2() {
        return this.releaseFg2;
    }

    public void setLiftOnFg1( String liftOnFg1 ) {
        this.liftOnFg1 = liftOnFg1;
    }
    public String getLiftOnFg1() {
        return this.liftOnFg1;
    }

    public void setLiftOnFg2( String liftOnFg2 ) {
        this.liftOnFg2 = liftOnFg2;
    }
    public String getLiftOnFg2() {
        return this.liftOnFg2;
    }

    public void setLiftOffFg1( String liftOffFg1 ) {
        this.liftOffFg1 = liftOffFg1;
    }
    public String getLiftOffFg1() {
        return this.liftOffFg1;
    }

    public void setLiftOffFg2( String liftOffFg2 ) {
        this.liftOffFg2 = liftOffFg2;
    }
    public String getLiftOffFg2() {
        return this.liftOffFg2;
    }

    public void setUpdatedUser( String updatedUser ) {
        this.updatedUser = updatedUser;
    }
    public String getUpdatedUser() {
        return this.updatedUser;
    }

    public void setUpdatedDtUtc( Date updatedDtUtc ) {
        this.updatedDtUtc = updatedDtUtc;
    }
    public Date getUpdatedDtUtc() {
        return this.updatedDtUtc;
    }

    public void setUpdatedDtServer( Date updatedDtServer ) {
        this.updatedDtServer = updatedDtServer;
    }
    public Date getUpdatedDtServer() {
        return this.updatedDtServer;
    }

    public void setExclusiveFg( String exclusiveFg ) {
        this.exclusiveFg = exclusiveFg;
    }
    public String getExclusiveFg() {
        return this.exclusiveFg;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(systemId);
        sb.append("|");
        sb.append(jobPatternCd);
        sb.append("|");
        sb.append(classCd);
        sb.append("|");
        sb.append(driverType);
        sb.append("|");
        sb.append(containerFg1);
        sb.append("|");
        sb.append(containerFg2);
        sb.append("|");
        sb.append(chassisFg1);
        sb.append("|");
        sb.append(chassisFg2);
        sb.append("|");
        sb.append(dockingFg1);
        sb.append("|");
        sb.append(dockingFg2);
        sb.append("|");
        sb.append(releaseFg1);
        sb.append("|");
        sb.append(releaseFg2);
        sb.append("|");
        sb.append(liftOnFg1);
        sb.append("|");
        sb.append(liftOnFg2);
        sb.append("|");
        sb.append(liftOffFg1);
        sb.append("|");
        sb.append(liftOffFg2);
        sb.append("|");
        sb.append(updatedUser);
        sb.append("|");
        sb.append(updatedDtUtc);
        sb.append("|");
        sb.append(updatedDtServer);
        sb.append("|");
        sb.append(exclusiveFg);
        return sb.toString(); 
    } 


}
