/*
 * Created on 14 Dec 2016 ( Time 17:21:18 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package jp.co.cyms.db;

import java.io.Serializable;

import java.util.Date;

/**
 * Java bean for 'TabJob' entity
 * 
 * @author DeNT
 *
 */
public class TabJob implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    // DB : SYSTEM_ID VARCHAR2 
    private String systemId;
    // DB : DRIVER_ID VARCHAR2 
    private String driverId;
    // DB : JOB_NO VARCHAR2 
    private String jobNo;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    // DB : UPDATED_DT_LOCAL TIMESTAMP(6) 
    private Date updatedDtLocal;

    // DB : BOOKING_NO VARCHAR2 
    private String bookingNo;

    // DB : CONTAINER_NO VARCHAR2 
    private String containerNo;

    // DB : HEAD_NO VARCHAR2 
    private String headNo;

    // DB : CHASSIS_NO VARCHAR2 
    private String chassisNo;

    // DB : DEPARTURE_TIME_FROM TIMESTAMP(6) 
    private Date departureTimeFrom;

    // DB : ARRIVAL_TIME_VIA TIMESTAMP(6) 
    private Date arrivalTimeVia;

    // DB : DEPARTURE_TIME_VIA TIMESTAMP(6) 
    private Date departureTimeVia;

    // DB : ARRIVAL_TIME_TO TIMESTAMP(6) 
    private Date arrivalTimeTo;

    // DB : COMPLETED_TIME TIMESTAMP(6) 
    private Date completedTime;

    // DB : DOCKING_TIME TIMESTAMP(6) 
    private Date dockingTime;

    // DB : LIFT_ON_TIME TIMESTAMP(6) 
    private Date liftOnTime;

    // DB : RELEASE_TIME TIMESTAMP(6) 
    private Date releaseTime;

    // DB : LIFT_OFF_TIME TIMESTAMP(6) 
    private Date liftOffTime;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setSystemId( String systemId ) {
        this.systemId = systemId ;
    }

    public String getSystemId() {
        return this.systemId;
    }

    public void setDriverId( String driverId ) {
        this.driverId = driverId ;
    }

    public String getDriverId() {
        return this.driverId;
    }

    public void setJobNo( String jobNo ) {
        this.jobNo = jobNo ;
    }

    public String getJobNo() {
        return this.jobNo;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setUpdatedDtLocal( Date updatedDtLocal ) {
        this.updatedDtLocal = updatedDtLocal;
    }
    public Date getUpdatedDtLocal() {
        return this.updatedDtLocal;
    }

    public void setBookingNo( String bookingNo ) {
        this.bookingNo = bookingNo;
    }
    public String getBookingNo() {
        return this.bookingNo;
    }

    public void setContainerNo( String containerNo ) {
        this.containerNo = containerNo;
    }
    public String getContainerNo() {
        return this.containerNo;
    }

    public void setHeadNo( String headNo ) {
        this.headNo = headNo;
    }
    public String getHeadNo() {
        return this.headNo;
    }

    public void setChassisNo( String chassisNo ) {
        this.chassisNo = chassisNo;
    }
    public String getChassisNo() {
        return this.chassisNo;
    }

    public void setDepartureTimeFrom( Date departureTimeFrom ) {
        this.departureTimeFrom = departureTimeFrom;
    }
    public Date getDepartureTimeFrom() {
        return this.departureTimeFrom;
    }

    public void setArrivalTimeVia( Date arrivalTimeVia ) {
        this.arrivalTimeVia = arrivalTimeVia;
    }
    public Date getArrivalTimeVia() {
        return this.arrivalTimeVia;
    }

    public void setDepartureTimeVia( Date departureTimeVia ) {
        this.departureTimeVia = departureTimeVia;
    }
    public Date getDepartureTimeVia() {
        return this.departureTimeVia;
    }

    public void setArrivalTimeTo( Date arrivalTimeTo ) {
        this.arrivalTimeTo = arrivalTimeTo;
    }
    public Date getArrivalTimeTo() {
        return this.arrivalTimeTo;
    }

    public void setCompletedTime( Date completedTime ) {
        this.completedTime = completedTime;
    }
    public Date getCompletedTime() {
        return this.completedTime;
    }

    public void setDockingTime( Date dockingTime ) {
        this.dockingTime = dockingTime;
    }
    public Date getDockingTime() {
        return this.dockingTime;
    }

    public void setLiftOnTime( Date liftOnTime ) {
        this.liftOnTime = liftOnTime;
    }
    public Date getLiftOnTime() {
        return this.liftOnTime;
    }

    public void setReleaseTime( Date releaseTime ) {
        this.releaseTime = releaseTime;
    }
    public Date getReleaseTime() {
        return this.releaseTime;
    }

    public void setLiftOffTime( Date liftOffTime ) {
        this.liftOffTime = liftOffTime;
    }
    public Date getLiftOffTime() {
        return this.liftOffTime;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(systemId);
        sb.append("|");
        sb.append(updatedDtLocal);
        sb.append("|");
        sb.append(driverId);
        sb.append("|");
        sb.append(jobNo);
        sb.append("|");
        sb.append(bookingNo);
        sb.append("|");
        sb.append(containerNo);
        sb.append("|");
        sb.append(headNo);
        sb.append("|");
        sb.append(chassisNo);
        sb.append("|");
        sb.append(departureTimeFrom);
        sb.append("|");
        sb.append(arrivalTimeVia);
        sb.append("|");
        sb.append(departureTimeVia);
        sb.append("|");
        sb.append(arrivalTimeTo);
        sb.append("|");
        sb.append(completedTime);
        sb.append("|");
        sb.append(dockingTime);
        sb.append("|");
        sb.append(liftOnTime);
        sb.append("|");
        sb.append(releaseTime);
        sb.append("|");
        sb.append(liftOffTime);
        return sb.toString(); 
    } 


}
